import matplotlib.pyplot as plt
import argparse
import csv

sheets = []
cells = []
items = []

# identify "ExceLint-eligible" sheets!
# there are at least two adjacent formulas (different or not)
#   number of suspicious ranges / number of rectangles
# produce an ExceLint-eligible filter
# also - omit any worksheets with no formulas (or "ineligible")

parser = argparse.ArgumentParser('plot-stats.py')
parser.add_argument('--input', help='Process an input .csv file, as generated by json-stats-to-csv.py.')
parser.add_argument('--output', help='Name of output graphic file.')

args = parser.parse_args()

if args.output is None or args.input is None:
    parser.print_help()
    exit(-1)

suspiciousnessThreshold = 0
formattingDiscount = 0;

with open(args.input, 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        workbookName = row['workbookName']
        worksheet = row['worksheet']
        suspiciousnessThreshold = row['suspiciousnessThreshold']
        numFormulaCells = row['numFormulaCells']
        # We don't bother with any sheet with one or fewer formulas, since ExceLint by definition will detect nothing.
        if int(numFormulaCells) > 1:
            # print(numFormulaCells)
            # Strip off .xlsx ending
            items.append((workbookName[:-5] + '!' + worksheet, row['suspiciousCells']))
        
sorted_items = sorted(items, key=lambda x: int(x[1]))

for item in sorted_items:
    if int(item[1]) > 0:
        sheets.append(item[0])
        cells.append(int(item[1]))
#    print(item[1])
    
max_cells = cells[-1]

plt.figure(figsize=(8,8))
plt.axes([0.1,0.2,0.9,0.7])
plt.title('ExceLint + CUSTODES: susp thresh = ' + str(suspiciousnessThreshold), y=1.02)
#plt.xlabel('Worksheet name')
plt.ylabel('# suspicious cells')
plt.ylim(0,max_cells)
plt.xticks(rotation='vertical', fontsize=4)
plt.tick_params(pad=0)
plt.bar(sheets, cells) # ['Foo', 'Bar'], [12, 13])
# plt.show()
plt.savefig(args.output, dpi=300)

